# Generated by Django 4.1.5 on 2023-03-07 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateDebute', models.CharField(default='', max_length=255)),
                ('DateFin', models.CharField(default='', max_length=255)),
                ('Pin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='membre1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateDebute', models.CharField(default='', max_length=255)),
                ('DateFin', models.CharField(default='', max_length=255)),
                ('Pin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Membres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_A', models.IntegerField(default=0)),
                ('position_B', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('ifLogged', models.BooleanField(default=False)),
                ('phonenumber', models.CharField(max_length=255)),
                ('token', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='workshop1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(max_length=255)),
                ('image_marque', models.CharField(max_length=255)),
                ('modele', models.CharField(max_length=255)),
                ('iftaken', models.BooleanField(default=False)),
                ('acceleration', models.CharField(max_length=255)),
                ('seat', models.IntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('pic', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('Users', models.ManyToManyField(through='mycar.membre1', to='mycar.user')),
            ],
        ),
        migrations.CreateModel(
            name='workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=255)),
                ('image_marque', models.CharField(max_length=255)),
                ('modele', models.CharField(max_length=255)),
                ('iftaken', models.BooleanField(default=False)),
                ('acceleration', models.CharField(max_length=255)),
                ('seat', models.IntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('pic', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('Users', models.ManyToManyField(through='mycar.membre', to='mycar.user')),
            ],
        ),
        migrations.CreateModel(
            name='Work_Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(max_length=255)),
                ('DateDebute', models.CharField(default='', max_length=255)),
                ('DateFin', models.CharField(default='', max_length=255)),
                ('Users', models.ManyToManyField(through='mycar.Membres', to='mycar.user')),
            ],
        ),
        migrations.AddField(
            model_name='membres',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycar.user'),
        ),
        migrations.AddField(
            model_name='membres',
            name='Work_Shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycar.work_shop'),
        ),
        migrations.AddField(
            model_name='membre1',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycar.user'),
        ),
        migrations.AddField(
            model_name='membre1',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycar.workshop1'),
        ),
        migrations.AddField(
            model_name='membre',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycar.user'),
        ),
        migrations.AddField(
            model_name='membre',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycar.workshop'),
        ),
    ]
