# Generated by Django 4.1.5 on 2023-03-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permis',
            field=models.IntegerField(default='0'),
        ),
    ]
