# Generated by Django 4.1.5 on 2023-03-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0002_user_permis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permis',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
