# Generated by Django 4.1.5 on 2023-03-07 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0003_alter_user_permis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permis',
        ),
    ]
